### ISSUE TITLE
Updating README.md

### ISSUE THREAD

**Issue by diosamuel** [diosamuel/redirect-url#1]
Just simple tool that help you redirecting the web.

[https://diosamuel.github.io/redirect-url/](https://diosamuel.github.io/redirect-url/)

[https://diosamuel.github.io/redirect-url?url=https://google.com](https://diosamuel.github.io/redirect-url?url=https://google.com)

[https://diosamuel.github.io/redirect-url?url=https://google.com&tab=true](https://diosamuel.github.io/redirect-url?url=https://google.com&tab=true)

Add readme.md for explain how to use this tool.

**Comment by diosamuel** [comment]
Thanks for @Nyanab for helping this issue

**Comment by Nyanab** [comment]
no problem
